### ISSUE TITLE
duplicate md code blocks

### ISSUE THREAD

**Issue by olarubaj** [life-itself/tao#6]
## Job Story
Fixing duplicate code blocks:

### Issues / Tasks page
![image](https://user-images.githubusercontent.com/104430201/167307887-1bbcaa43-ea82-4e58-97a3-05f9688f6323.png)

![image](https://user-images.githubusercontent.com/104430201/167307974-60ed5702-bb79-4883-be1d-bbe5295ca7c5.png)

### Onboarding page
![image](https://user-images.githubusercontent.com/104430201/167307941-bdd5ae29-5486-4783-8a2c-f25e1788dbdc.png)

## Acceptance
* code blocks with md not showing duplicate blocks on the rendered site

## Tasks
* [ ] investigate why the code blocks with markdown in various places are converted to multiple same sections in html

**Comment by rufuspollock** [comment]
WONTFIX. Leaving this for now (this repo is being archived). Can come back to this on new repo if issue still shows up.
